[package]
name = "stop-token"
version = "0.1.3"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/async-rs/stop-token"

description = "Experimental cooperative cancellation for async-std"

[dependencies]
pin-project-lite = "0.1.0"
futures = "0.3.5"
event-listener = "2.2.0"


[dev-dependencies]
async-std = { version = "1.0", features = ["unstable"] }

[features]
unstable = []
# This feature doesn't do anything anymore,
# but is needed for backwards-compatibility
