name: CI

on:
  pull_request:
  push:
    branches:
      - staging
      - trying
      - master

env:
  RUSTFLAGS: -Dwarnings

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Install nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true

    - name: tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --features runtime
